const express = require('express');
const controller = require('../controllers/userController');
const { requireAuth } = require('../middleware/authMiddleware');
const router = express.Router();
router.use(requireAuth);
router.get('/', controller.list);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.patch('/:id/status', controller.updateStatus);
module.exports = router;